---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Services:
    - Plex:
        icon: plex.png
        href: http://localhost/
        description: Media Server
        server: docker-proxy
        container: plex
        widget:
            type: plex
            url: http://localhost:32400
            key: ${PLEX_SERVER_TOKEN} # see https://www.plexopedia.com/plex-media-server/general/plex-token/
    - Hoarder:
        icon: hoarder.png
        href: http://localhost:3000
        description: Read it later app
        server: docker-proxy
        container: hoarder-web-1