services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PLEX_UID=1000
      - PLEX_GID=1000
      - TZ=America/Chicago
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN}
    env_file:
      - ../.env
    network_mode: host
    volumes:
      - /opt/stacks/plex/config:/config
      - /opt/stacks/plex/transcode:/transcode
      - /opt/stacks/plex/media:/data